// <auto-generated />
namespace Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addMainVideoFeedToNews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMainVideoFeedToNews));
        
        string IMigrationMetadata.Id
        {
            get { return "202408040452008_addMainVideoFeedToNews"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
